#!/usr/bin/env bash
# Publish queued SSK Music blog posts.
#
#   bash scripts/blog-publish.sh <slug> [<slug>...]
#   bash scripts/blog-publish.sh            # publishes whatever is in posts/
#
# BigHeadz publishes into Neon because it's a Next.js app with a database.
# This site is static on Cloudflare Pages, so publishing IS the git push:
# regenerate the pages, commit, push, and Pages rebuilds. That means there is
# no separate "published" state to drift out of sync — what's in the repo is
# what's live, which is the opposite of the BigHeadz setup and worth
# remembering when reading across the two.
#
# Verification is not optional. A push that Pages fails to build leaves the
# post invisible while every local signal says success, so this polls the real
# URL and exits non-zero if it never returns 200.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SITE="https://sskmusic.com"
DEPLOY_TIMEOUT="${DEPLOY_TIMEOUT:-300}"   # seconds to wait for Pages
cd "$REPO"

log() { echo "[blog-publish] $(date -Is) $*"; }

# --- work out what we're publishing -----------------------------------------
SLUGS=("$@")
if [[ ${#SLUGS[@]} -eq 0 ]]; then
  shopt -s nullglob
  for f in data/blog/posts/*.json; do
    SLUGS+=("$(basename "$f" .json)")
  done
fi
if [[ ${#SLUGS[@]} -eq 0 ]]; then
  log "nothing to publish"; exit 0
fi
log "slugs: ${SLUGS[*]}"

# --- rebuild ----------------------------------------------------------------
git pull --ff-only origin main >/dev/null 2>&1 || log "WARN pull skipped"

# Voice lint is a hard gate, not a warning. BigHeadz's equivalent step calls
# a script (scripts/audit-blog-copy.ts) that was never committed to that
# repo, so it has failed and been waved through on every run since the
# pipeline was written. This one exists, runs, and blocks the push on a
# FAIL — that's the whole point of building it.
for slug in "${SLUGS[@]}"; do
  if ! node scripts/blog-voice-lint.mjs "$slug"; then
    log "BLOCKED — $slug failed the voice lint. Fix the post and re-run."
    exit 1
  fi
done

node scripts/build-blog.mjs
node scripts/stamp-assets.mjs >/dev/null 2>&1 || true

# --- commit -----------------------------------------------------------------
git add -A
if git diff --cached --quiet; then
  log "no changes to commit — already published?"
else
  TITLE=$(node -e "
    const fs=require('fs');
    const s=process.argv[1];
    try { console.log(JSON.parse(fs.readFileSync('data/blog/posts/'+s+'.json','utf8')).title||s); }
    catch { console.log(s); }
  " "${SLUGS[0]}")
  EXTRA=""
  [[ ${#SLUGS[@]} -gt 1 ]] && EXTRA=" (+$(( ${#SLUGS[@]} - 1 )) more)"
  git commit -q -m "Blog: ${TITLE}${EXTRA}

Generated by the scheduled writer. Pages rebuilt by scripts/build-blog.mjs."
  git push -q origin main
  log "pushed $(git rev-parse --short HEAD)"
fi

# --- verify live ------------------------------------------------------------
FAILED=()
for slug in "${SLUGS[@]}"; do
  url="$SITE/blog/$slug"
  log "waiting for $url"
  deadline=$(( $(date +%s) + DEPLOY_TIMEOUT ))
  ok=0
  while [[ $(date +%s) -lt $deadline ]]; do
    code=$(curl -s -o /dev/null -w '%{http_code}' -L "$url" || echo 000)
    if [[ "$code" == "200" ]]; then ok=1; log "  200 OK"; break; fi
    sleep 15
  done
  [[ $ok -eq 1 ]] || { log "  FAILED — never returned 200"; FAILED+=("$slug"); }
done

# the listing must show it too, or the post exists but nobody can find it
listing=$(curl -s -o /dev/null -w '%{http_code}' -L "$SITE/blog" || echo 000)
log "listing /blog -> $listing"

if [[ ${#FAILED[@]} -gt 0 ]]; then
  log "PUBLISH INCOMPLETE: ${FAILED[*]}"
  exit 1
fi
log "done — ${#SLUGS[@]} post(s) live"
